# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "capistrano-tinderfields"
  s.version = "0.0.17"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Paul Odeon"]
  s.date = "2013-07-18"
  s.description = "Tinderfields recipes for Capistrano"
  s.email = "paul@tinderfields.com"
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "README",
    "Rakefile",
    "VERSION",
    "capistrano-tinderfields.gemspec",
    "lib/tinderfields/capistrano/asset.rb",
    "lib/tinderfields/capistrano/assets.rb",
    "lib/tinderfields/capistrano/base.rb",
    "lib/tinderfields/capistrano/cake.rb",
    "lib/tinderfields/capistrano/common.rb",
    "lib/tinderfields/capistrano/console.rb",
    "lib/tinderfields/capistrano/database.rb",
    "lib/tinderfields/capistrano/database_tasks.rb",
    "lib/tinderfields/capistrano/database_yaml.rb",
    "lib/tinderfields/capistrano/delayed_job.rb",
    "lib/tinderfields/capistrano/maintenance.rb",
    "lib/tinderfields/capistrano/passenger_standalone.rb",
    "lib/tinderfields/capistrano/php.rb",
    "lib/tinderfields/capistrano/solr.rb",
    "lib/tinderfields/capistrano/symlinks.rb",
    "lib/tinderfields/capistrano/tail.rb",
    "lib/tinderfields/capistrano/templates/database.php.erb",
    "lib/tinderfields/capistrano/templates/database.yml.erb",
    "lib/tinderfields/capistrano/templates/database_details.php.erb",
    "lib/tinderfields/capistrano/templates/wp-config.php.erb",
    "lib/tinderfields/capistrano/util.rb",
    "lib/tinderfields/capistrano/wordpress.rb"
  ]
  s.homepage = "http://tinderfields.com"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Tinderfields recipes for Capistrano"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<capistrano>, [">= 0"])
      s.add_runtime_dependency(%q<capistrano-ext>, [">= 0"])
      s.add_runtime_dependency(%q<capistrano_colors>, [">= 0"])
      s.add_runtime_dependency(%q<rvm-capistrano>, [">= 0"])
    else
      s.add_dependency(%q<capistrano>, [">= 0"])
      s.add_dependency(%q<capistrano-ext>, [">= 0"])
      s.add_dependency(%q<capistrano_colors>, [">= 0"])
      s.add_dependency(%q<rvm-capistrano>, [">= 0"])
    end
  else
    s.add_dependency(%q<capistrano>, [">= 0"])
    s.add_dependency(%q<capistrano-ext>, [">= 0"])
    s.add_dependency(%q<capistrano_colors>, [">= 0"])
    s.add_dependency(%q<rvm-capistrano>, [">= 0"])
  end
end

