begin
  require 'jeweler'
  Jeweler::Tasks.new do |gemspec|
    gemspec.name = "capistrano-tinderfields"
    gemspec.summary = "Tinderfields recipes for Capistrano"
    gemspec.description = "Tinderfields recipes for Capistrano"
    gemspec.email = "paul@tinderfields.com"
    gemspec.homepage = "http://tinderfields.com"
    gemspec.authors = ["Paul Odeon"]
    
    gemspec.add_dependency 'capistrano'
    gemspec.add_dependency 'capistrano-ext'
    gemspec.add_dependency 'capistrano_colors'
    gemspec.add_dependency 'rvm-capistrano'
    gemspec.files.include Dir.glob('lib/**/*.rb')
    gemspec.files.include Dir.glob('lib/**/*.erb')
  end
rescue LoadError
  puts "Jeweler not available. Install it with: gem install jeweler"
end